config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'project', to: 'pages#project'
  get 'product', to: 'pages#product'
  get 'research', to: 'pages#research'
   get 'contact', to: 'pages#contact'

  # resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "inanna.craigmorse@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contacts_params)
    @contact.request = request
    if @contact.deliver
      redirect_to "http://www.awarenessvr.org"
    else
      render :new
    end
  end

  def contacts_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def project
  end

  def product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<br>
<br>

<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3 mt-5 p-5 justify-content">

      <h3>We would love to hear from you!</h3>
      <br>

        <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
          <%= f.input :name, :required => true, label: "Your full name" %>
          <%= f.input :email, :required => true %>
          <%= f.input :message, :as => :text, :required => true %>

          <div>
            </br>
            <%= f.button :submit, 'Send message', :class=> "btn" %>
          </div>
      <% end %>

  </div>
</div>

app/views/layouts/_custom_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px;">AWARENESS VR</span>
    <% end %>

<div class="d-flex flex-end">
        <div class="nav-item">
          <%= link_to "about", about_path, class: "nav-link" %>
        </div>

          <div class="nav-item">
          <%= link_to "contact", about_path, class: "nav-link" %>
        </div>


</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <meta name="description" content="<%= meta_description %>">
    <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />

    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Awareness VR</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body style="background-color: white;">
    <%#= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: #121212;">AWARENESS VR</span>
    <% end %>

<div class="d-flex flex-end " >
        <div class="nav-item">
          <%= link_to "about", about_path, class: "nav-link-2" %>
        </div>

          <div class="nav-item">
          <%= link_to "what it is", what_it_is_path, class: "nav-link-2" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link-2" %>
        </div>
</div>

</div>
<br>

<div class="container justify-content-center align-items-center mt-3">
  <div class="d-flex flex-column justify-content-center align-items-center p-3 mt-5">
<br>

    <h1>About</h1>
    <br>
    <p>Thanks for visiting! Awareness VR is a project dedicated to helping users explore their relationship to their mind and reality through out of body VR experiences. </p>




    <p>Out of body experiences can deepen our meditations and help us understand ourselves as being part of something 'bigger". Much of our sense of reality has to do with our visual perceptions (we see the world and assume that's how it is). As VR becomes more widespread, it can provide visual aids to help us experience reality without the influence of our regular visual perceptions.</p>
    <p>Having meditated for many years, I attended the London School of Economics, where I focused on how innovation can spark new ways of expanding the benefits of meditation. This project is the culmination my dissertation and informed by numerous interviews with VR labs and meditation experts.</p>

   <%= image_tag "profile.jpg", height: 350, width: 350, alt: "alttext", class: "image" %>
   <br>

      <p>Previously I worked at Human Rights Watch and was a Fulbright scholar to India. </p>

  </div>

</div>

app/views/pages/contact.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: #121212;">Awareness VR</span>
    <% end %>

<div class="d-flex flex-end " >
        <div class="nav-item">
          <%= link_to "project", project_path, class: "nav-link-2" %>
        </div>

          <div class="nav-item">
          <%= link_to "product", product_path, class: "nav-link-2" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link-2" %>
        </div>
</div>

</div>



  <br>
  <br>

  <div class="row">
  <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3 mt-5 p-5 justify-content">

   <h3>We would love to hear from you!</h3>
   <br>

  <form  method="POST" action="https://simple-form.com/inanna.craigmorse@gmail.com">
        <input type="hidden" name="redirectURL" value="http://awarenessvr.org" />
        <input class="form-control" type="text" name="name" placeholder="Your name" />
        <br>

        <input class="form-control" type="email" name="replyTo" placeholder="Your email" />
        <br>

        <textarea class="form-control" name="message" placeholder="Your message"></textarea>
        <br>

        <input type="submit" value="Send" class="btn"/>

        </form>

 </div>
</div>

app/views/pages/home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: white">Awareness VR</span>
    <% end %>

<div class="d-flex flex-end">
        <div class="nav-item">
          <%= link_to "project", project_path, class: "nav-link"%>
        </div>

          <div class="nav-item">
          <%= link_to "product", product_path, class: "nav-link" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link" %>
        </div>
</div>

</div>


<div class="home d-flex justify-content-center align-items-center ";>

  <div class="home-1 d-flex p-3 justify-content-center align-items-center">

      <div class="test d-flex flex-column justify-between align-items-center">

        <div class="p-1"><h1>AWARENESS VR</h1></div>
        <div class="p-1"><h2>Meditative, out-of-body virtual reality experiences, prompting exploration into the relationship between our mind and reality</h2></div>



      </div>
  </div>

</div>

app/views/pages/product.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: #121212;">Awareness VR</span>
    <% end %>

<div class="d-flex flex-end " >
        <div class="nav-item">
          <%= link_to "project", project_path, class: "nav-link-2" %>
        </div>

          <div class="nav-item">
          <%= link_to "product", product_path, class: "nav-link-2" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link-2" %>
        </div>
</div>

</div>
<br>


  <div class="container justify-content-center align-items-center mt-5">
  <div class="d-flex flex-column justify-content-center align-items-center p-3 mt-5">

      <br>
      <h1>Product</h1>
      <br>

      <p>The product will be a series of guided, meditative sessions in VR that walk users through exploring the connection between their mind and reality. The style of sessions will be similar to those of Sam Harris on his Waking Up app (though in VR); exercises will have the implicit orientation of guiding users towards an awakened state/self-transcendence. The sessions build off the idea that experiencing the world through VR makes us question our reality outside of the VR headset. Consistent use of the exercises may provide mental health benefits. </p>

      <p>Similar to the style of widely used non-VR meditation apps (Calm,
Headspace, Waking Up), a narrator guides the meditation, meditations build
off of each other, and each course will focus on various aspects of meditation (see examples below). Content will be based on self-transcendence and mental health research. </p>
<br>
<h1>Examples of exercises</h2>
<br>
<p>Experiencing "headlessness" by looking into a mirror and seeing yourself as someone else, and then seeing yourself as nothing.</p>
<%= image_tag "mirror.jpg", height: 450, width: 450, alt: "alttext", class: "image"%>
<br>
<br>
<p>Experimenting with gravity by turning your environment upside down.</p>
<%= image_tag "upside down.jpg", height: 480, width: 450, alt: "alttext", class: "image" %>
<br>
<br>
<p>Merging with natural surroundings, such as by breathing with waves.</p>
<%= image_tag "waves.jpg", height: 450, width: 450, alt: "alttext", class: "image" %>
    </div>

  </div>

app/views/pages/project.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: #121212;">Awareness VR</span>
    <% end %>

<div class="d-flex flex-end " >
        <div class="nav-item">
          <%= link_to "project", project_path, class: "nav-link-2" %>
        </div>

          <div class="nav-item">
          <%= link_to "product", product_path, class: "nav-link-2" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link-2" %>
        </div>
</div>

</div>
<br>

<div class="container justify-content-center align-items-center mt-3">
  <div class="d-flex flex-column justify-content-center align-items-center p-3 mt-5">
<br>

    <h1>About</h1>
    <br>
    <p>Awareness VR is a project dedicated to helping users explore their relationship to their mind and reality through out-of-body VR experiences. </p>




    <p>Out-of-body experiences can deepen our meditations and help us understand ourselves as being part of something 'bigger". Much of our sense of reality has to do with our visual perceptions (we see the world and assume that's how it is). As VR becomes more widespread, it can provide visual aids to help us experience reality without the influence of our regular visual perceptions.</p>
    <p>Having meditated for many years, I attended the London School of Economics, where I focused on how innovation can spark new ways of expanding the benefits of meditation. This project is the culmination my dissertation and informed by numerous interviews with VR labs and meditation experts.</p>

   <%= image_tag "profile.jpg", height: 350, width: 350, alt: "alttext", class: "image" %>
   <br>

      <p>I've worked in finance and the non-profit sector and was a Fulbright scholar to India. </p>
      <a href="https://www.linkedin.com/in/inanna-craig-morse/" class="icon-black"><i class="fab fa-linkedin"></i></a>

  </div>

</div>

app/views/pages/research.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: #121212;">AWARENESS VR</span>
    <% end %>

<div class="d-flex flex-end " >
        <div class="nav-item">
          <%= link_to "about", about_path, class: "nav-link-2" %>
        </div>

          <div class="nav-item">
          <%= link_to "what it is", what_it_is_path, class: "nav-link-2" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link-2" %>
        </div>
</div>

</div>


<br>

<div class="container justify-content-center align-items-center mt-3">
  <div class="d-flex flex-column justify-content-center align-items-center p-5 mt-5">
    <br>

    <h1>Mental health</h1>
    <p class="p-2">Mental health in the UK is a widespread challenge that disproportionally affects impoverished youth. </p>


<%= image_tag "data.png", height: 250, width: 650, alt: "alttext" %>

<br>
<br>
<h1>Meditation</h1>
    <p>Meditation is a recommended tool to manage mental health (4), and has been successfully integrated into 370 UK schools (5).</p>

   <%= image_tag "circles.png", height: 250, width: 750, alt: "alttext" %>
   <br>

      <p>However, children aged 5-15 continue to find meditation challenging to learn and difficult to apply to their daily lives. </p>

      <%= image_tag "icons.png", height: 280, width: 600, alt: "alttext" %>
      <br>
      <br>

  <h1>Virtual Reality</h1>

    <p>Virtual reality meditation exercises can help overcome these barriers. </p>

       <%= image_tag "circles2.png", height: 220, width: 730, alt: "alttext" %>
   <br>
<br>

<h1>Vision</h1>
<p>Our mission is to significantly reduce rates of mental health issues among low-income youth in the UK by using easy-to-learn vr meditation exercises to help give them the lifelong resource of meditation. We hope that this will inspire related iniatives elsewhere.  </p>
      <%= image_tag "woman1.jpg", height: 400, width: 550, alt: "alttext" %>
      <br>
      <br>

<h1>References</h1>
<ol>
  <li style="font-size: 13px;">Social Metrics Commission 2019 Report:https://socialmetricscommission.org.uk/social-metrics-commission-results-tables-2/</li>
<li style="font-size: 13px;" >Saving Lives: Our healthier nation, Department of Health, 1999 https://www.gov.uk/Government/uploads/ system/uploads/attachment_data/file/265576/4386.pdf</li>
<li style="font-size: 13px;">Mental Health: Poverty, ethnicity and family breakdown, Centre for Social Justice, 2011 http://www. centreforsocialjustice.org.uk/UserStorage/pdf/Pdf%20reports/MentalHealthInterimReport.pdf</li>
<li style="font-size: 13px;">Mental Health Organization, NHS, Harvard Medical School, Center for Anxiety and Traumatic Stress Disorders, Cambridge Health Alliance, University of Massachusetts Medical Center</li>
<li style="font-size: 13px;">Nytimes.com. (2019). Schools in England Introduce a New Subject: Mindfulness. [online] Available at: https://www.nytimes.com/2019/02/04/world/europe/uk-mindfulness-children-school.html [Accessed 24 Nov. 2019].</li>
<li style="font-size: 13px;">Lutz, A., Slagter, H. A., Dunne, J. D., & Davidson, R. J. (2008). Attention regulation and monitoring in meditation. Trends in Cognitive Sciences, 12(4), 163–169.</li>
<li style="font-size: 13px;">Metz, S. M., Frank, J. L., Reibel, D., Cantrell, T., Sanders, R., & Broderick, P. C. (2013). The effectiveness of the learning to BREATHE program on adolescent emotion regulation. Research in Human Development, 10(3), 252–272.</li>
<li style="font-size: 13px;">Liehr, P., & Diaz, N. (2010). A Pilot Study Examining the Effect of Mindfulness on Depression and Anxiety for Minority Children. Archives of Psychiatric Nursing, 24(1), 69–71.</li>
<li style="font-size: 13px;">Jones, A. (2013, June 10). Meditation in schools: calming minds and beating stress. Retrieved from https://www.theguardian.com/teacher-network/teacher-blog/2013/jun/10/meditation-mindfulness-schools-stress-calming-classrooms.</li>
<li style="font-size: 13px;">Navarro-Haro MV, López-del-Hoyo Y, Campos D, Linehan MM, Hoffman HG, García-Palacios A, et al. (2017) Meditation experts try Virtual Reality Mindfulness: A pilot study evaluation of the feasibility and acceptability of Virtual Reality to facilitate mindfulness practice in people attending a Mindfulness conference. PLoS ONE 12(11): e0187777.https://doi.org/10.1371/journal.pone.0187777</li>
<li style="font-size: 13px;">Isacsson, D. (2016, February 1). Report: Youths Want Virtual Reality. Retrieved from https://www.digitaltrends.com/virtual-reality/report-youths-want-vr/.</li>

</ol>



  </div>

</div>

app/views/pages/what_it_is.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: #121212;">AWARENESS VR</span>
    <% end %>

<div class="d-flex flex-end " >
        <div class="nav-item">
          <%= link_to "about", about_path, class: "nav-link-2" %>
        </div>

          <div class="nav-item">
          <%= link_to "what it is", what_it_is_path, class: "nav-link-2" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link-2" %>
        </div>
</div>

</div>
<br>


  <div class="container justify-content-center align-items-center mt-5">
  <div class="d-flex flex-column justify-content-center align-items-center p-3 mt-5">

      <br>
      <h1>Product</h1>
      <br>

      <p>The goal of this project is to create and make available a series of guided, meditative sessions in VR that walk users through exploring the connection between their mind and reality. The style of sessions will be similar to those of Sam Harris on his Waking Up app (though in VR); exercises will have the implicit orientation of guiding users towards an awakened state/self-transcendence. The sessions build off the idea that experiencing the world through VR makes us question our reality outside of the VR headset. Consistent use of the exercises may provide mental health benefits. </p>

      <p>Similar to the style of widely used non-VR meditation apps (Calm,
Headspace, Waking Up), a narrator guides the meditation, meditations build
off of each other, and each course will focus on various aspects of meditations (see examples below). Content will be based self-transcendence and mental health research and will be built for Quest  </p>
<br>
<h1>Examples of exercises</h2>
<br>
<p>Experiencing "headlessness" by looking into a mirror and seeing yourself as someone else, and then seeing yourself as ntohing.</p>
<%= image_tag "mirror.jpg", height: 450, width: 450, alt: "alttext", class: "image"%>
<br>
<br>
<p>Experimenting with gravity by turning your environment upside down.</p>
<%= image_tag "upside down.jpg", height: 480, width: 450, alt: "alttext", class: "image" %>
<br>
<br>
<p>Merging with natural surroundings, such as by breathing with waves.</p>
<%= image_tag "waves.jpg", height: 450, width: 450, alt: "alttext", class: "image" %>
    </div>

  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
   <span style="padding-left: 16px; color: white">Awareness VR</span>
    <% end %>

<div class="d-flex flex-end">
        <div class="nav-item">
          <%= link_to "project", project_path, class: "nav-link" %>
        </div>

          <div class="nav-item">
          <%= link_to "product", product_path, class: "nav-link" %>
        </div>



        <div class="nav-item ">
          <%= link_to "contact", contact_path, class: "nav-link" %>
        </div>
</div>

</div>